FORMAT: 1A
HOST: https://api.fashion.cloud/v2

# Fashion Cloud API v2

This is the documentation of the **Fashion Cloud API v2**.\
\
\
To receive **Email Updates** for changes and improvements to our API, please subscribe [**here**](https://form.typeform.com/to/cBDOjWOP)!
\
\
Following this [**link**](https://www.notion.so/fashioncloud/Fashion-Cloud-API-ed2b17970caf4782a666a2f0661bd701)  you can find **additional documentation** that displays possible values of our product endpoint and also provides a guide on how to synchronise data\
\
\
**How to use the API:**
In order to use the API you need to get an **Auth Token** that you can get by creating an account on our platform (https://app.fashion.cloud/#/signup?role=retailer).
But before you can get started using the API we will need to enable your account to be allowed to use the API, please get in touch with us to do that.
**Attention**: The parameters are always stated in the URL, also the token.

## Brands Collection [/brands]

### List Brands [GET /brands{?token,offset,limit,gln}]

The brands collection contains the data about all brands that participate on Fashion Cloud. For each brand the endpoint also returns the permissions the client has on the different resources of the brand.
[**Check here**](https://www.notion.so/fashioncloud/Brand-endpoint-5c34b43780744b09a2ef47529fb99a86) for detailed attribute description

+ Parameters
    + token (String) - Your Fashion Cloud API Key/Token, mandatory
    + offset (Number, optional) - The offset (of items to be returned) for the pagination (default = 0), optional but the response will always be paginated
    + limit (Number, optional) - The amount of items to return per page (default = 200), optional, max value is 200
    + gln (String, optional) - Filters the items by the given gln, optional
    
+ Request

    + Headers

            Accept: application/json

+ Response 200 

    + Headers

            Date: 2017-04-01T01:00:00.000Z
            Content-Type: application/json
            Content-Encoding: Gzip, deflate
            Content-Language: de

    + Body
    
            {
                "offset": 0,
                "limit": 100,
                "totalElements": 100000,
                "data": [{
                    "_id": "5879212",
                    "name": "BRAX",
                    "description": "BRAX erzählt von Leidenschaft:  Leidenschaft, Kunden für unsere Produkte zu begeistern. Diese Leidenschaft begleitet uns bei jedem Vorhaben und sämtlichen Entscheidungen unseres täglichen Handelns.",
                    "glns": ["4029163000074", "4029163000098", "4029163000708"],
                    "logo": "logo_5a33da1796cc636a2cb24f59",
                    "premium": true, // wheter or not this is a premium brand
                    // products meta data
                    "products": {
                        "available": true,
                        "updated": "2017-01-01T12:00:00.000Z", // ISO 8601
                    },
                    // marketing files meta data
                    "marketingFiles": {
                        "available": false,
                        "updated": null
                    },
                    // reorders meta data
                    "reorders": {
                        "available": true
                    },
                    // users permissions for this brand
                    "permissions": {
                        "products": {
                            "erp": true,
                            "ecommerce": false,
                            "digitalWindow": true
                        },
                        "marketingFiles": true,
                        "reorders": true
                    },
                    "created": "2016-12-01T01:00:00.000Z"
                }]
            }


## Products Collection [/products]

### List Products [GET /products{?token,offset,afterId,limit,updatedSince,lang,brand,gtin,gtin,articleNumber,includePreliminary,season,seasonYear}]

Additional requirements:

    * One filter must at least be used (brand, gtin or articleNumber. gtin and articleNumber may not be used at the same time)
    
[**Check here**](https://www.notion.so/fashioncloud/Product-endpoint-3fad597ecaef498ba2e37dcc2cebf37f) for detailed attribute description

The attributes `styleGroupId` and `colorGroupId` allow the grouping of products. Within a brand, the `styleGroupId` identifies all connected GTINs and product variants (e.g. colors). The combination of `styleGroupId` and `colorGroupId` within a brand is the same for all sizes of a color variant.
![product grouping](https://s3.eu-central-1.amazonaws.com/fashioncloud-static-images/apiaryImages/stylegroup.png)



+ Parameters
    + token (String) - Your Fashion Cloud API Key/Token, mandatory
    + offset (Number, optional) - Please use "afterId" instead for better performance - The offset (of items to be returned) for the pagination (default = 0), optional but the response will always be paginated
    + afterId (String, optional) - The "nextId" of the response body in order to get the next page. This is a lot more performant than using offset, which is not recommendet to use anymore!
    + limit (Number, optional) - The amount of items to return per page (default = 200), optional, max value is 1000
    + updatedSince (ISO Date String, optional) - Only get products that have been updated or created since the given date, optional
    + lang (String, optional) - The language filter (default = 'de'), [check here](https://www.notion.so/fashioncloud/Product-endpoint-3fad597ecaef498ba2e37dcc2cebf37f#730fdf24afe94952bc11474e7d6e78f3) for possible values, optional
    + brand (String, optional) - The brand id that you can retrieve from the /brands endpoint, either brand, or gtin, or articleNumber must be provided
    + gtin (String, optional) - The GTIN filter, either brand, or gtin, or articleNumber must be provided
    + articleNumber (String, optional) - The article number filter, either brand, or gtin, or articleNumber must be provided
    + includePreliminary (boolean, optional) - Whether or not to include preliminary images in the media.images array, optional
    + season (String, optional) - The season filter, possible values are: ['fall_winter', 'spring_summer', 'nos', 'none'], "none" will return all products that does not have a season assigned, optional
    + seasonYear (String, optional) - The season year filter (This is ignored when season is 'nos'), optional
    + includeProductsWithoutImages (boolean, optional) - Whether or not to include products without images in the media.images array, default option is false, optional
    
+ Request

    + Headers

            Accept: application/json

+ Response 200 

    + Headers

            Date: 2017-04-01T01:00:00.000Z
            Content-Type: application/json
            Content-Language: de (or en, fr, etc)

    + Body
    
            {
                //Attributes in this example don't match up to an actual article, we are simply demonstrating possible values. 
                "offset": 0, // only returned if parameter "offset" was used, which is not recommended anymore!
                "nextId": "12345", // use this value as the "afterId" for the next call in order to get the next page
                "afterId": "123", // only returned if parameter "afterId" was used
                "limit": 100,
                "totalElements": 100000,
                "data": [{
                    "_id": "12345",
                    "gtin": "1234567890123",
                    "articleNumber": "abc-123",
                    "styleGroupId": "abc",
                    "colorGroupId": "312",
                    "brand": {
                        "_id": "1234567890"
                    },
                    "manufacturerAttributes": { //ManufacturerAttributes are the values as we receive them from brands
                        "name": "Jeans Jacket",
                        "description": "A fashionable men's jeans jacket with fine details",
                        "shortDescription": "Fashionable Mens Jacket",
                        "size": "31/32",
                        "colorCode": "312",
                        "bteCode": "110210",
                        "fedasCode": "275277",
                        "colorName": "stone wash blue",
                        "material": "Lining 1: 100% Polyester;Shell: 61% Elastomultiester - SoronaÂ®, 39% Polyester",
                        "category": "Outerwear", 
                        "functions": "THERMAL",
                        "occasion": "This layering piece works well with a coat, or shacket, but it can also stand alone",
                        "fit": "Regular fit",
                        "closure": "Half zip fastening",
                        "collection": "ESS AUTUMN 2025",
                        "sleeveLength": "Long sleeves",
                        "neckline": "Hoodie",
                        "manufacturedIn": "CN",
                        "detailedSize": {
                            "size": "36",
                            "subSize": "32",
                            "sizeType": "length",
                            "sizeSystem": "EU",
                            "subSizeType": "width"
                        }
                        "certificates":[
                            {
                                "value": "Global Organic Textile Standard 'Organic'",
                                "coverage": 100,
                                "labelGrade": "Product",
                                "visibleOnProduct": true,
                                "certificateNumber": "91104921",
                                "certifyingInstitute": "Control Union"
                            }
                        ]}
                    //find even more manufacturerAttributes here https://fashioncloud.notion.site/Product-endpoint-3fad597ecaef498ba2e37dcc2cebf37f?pvs=4
                    },
                    "fcAttributes": { //FcAttributes are mapped and translated values
                        "ageGroup": "Adults",
                        "targetGroup": "Men",
                        "detailedCategory": "Parkas",
                        "category": "Outdoor jackets", //find our complete category tree in additional docs. https://www.notion.so/fashioncloud/Fashion-Cloud-API-ed2b17970caf4782a666a2f0661bd701
                        "material": "lining material: 100% polyester; outer fabric: 61% elastomultiester, 39% polyester",
                        "searchColors": ["Blue", "Red"],
                        "season": "Spring/Summer 2017",
                        "careInstruction": [
                            "40°C coloured wash",
                            "Do not bleach",
                            "Do not tumble dry",
                            "Iron at low temperature",
                            "Do not dry-clean"
                        ],
                    },
                    "fcKeys": { //fcKeys are mapped in complete detail
                        "ageGroup": "adults",
                        "targetGroup": "male",
                        "materials": [
                        {
                            "partName": "liningmaterial",
                            "composition": [
                                {
                                    "material": "polyester",
                                    "percentage": "100"
                                }
                            ]
                        },
                        {
                            "partName": "outerfabric",
                            "composition": [
                                {
                                    "material": "elastomultiester",
                                    "percentage": "61"
                                },
                                {
                                    "material": "polyester",
                                    "percentage": "39"
                                }
                            ]
                        }],
                        "searchColors": ["blue", "red"],
                        "season": "spring_summer",
                        "seasonYear": "2017",
                        "careInstruction": [
                        "1_B_40",
                        "2_X",
                        "3_X",
                        "4_110",
                        "5_DX"
                        ],
                        "animalParts": "false",
                        "detailedCategory": {
                            "top": "clothing",
                            "main": "outdoorJackets",
                            "level1": [
                                "parkas"
                        ]},
                    },
                    "media": {
                        "images": [{
                            "_id": "123",
                            "isMainImage": true,
                            "hash": "abc",
                            "shootType": "hollow",
                            "productView": "front"
                        }]
                    },
                    "permissions": {
                        "erp": true,
                        "ecommerce": false,
                        "digitalWindow": true
                    },
                    "created": "2016-12-01T01:00:00.000Z",
                    "updated": "2016-12-02T01:00:00.000Z"
                }]
            }


### Load Product Image [GET /products/media/images/{id}{?token,px,watermark,minAcceptableSize}]

* In order to get images without watermark your account needs to be upgraded. Please let us know if you wish to get e-commerce quality images.
* Images will always be returned as Content-type 'image/jpeg'
* **Important:** If you want to use the images for eCom, you **have to add the `watermark=false` parameter**. Only then you will only receive images without watermark

+ Parameters
    + id (String) - The image _id, mandatory
    + token (String) - Your Fashion Cloud API Key/Token, mandatory
    + px (number, optional) - The pixel size of the image, possible values are ["200", "512", "1024"]. Optional, when omitted the original image size will be returned
    + watermark (Boolean, optional) - Requests the image with or without Fashion Cloud watermark. For images without watermark the user has to have the "ecommerce" or "digitalWindow" permission. Optional, when omitted the non watermarked image is returned if possible, otherwise the watermarked one
    + minAcceptableSize (String, optional) - The minimum acceptable size of the image. Possible values are ["200", "512", "1024"]. If the image is not available in the requested size this parameter allows falling back to smaller sizes until the defined minimum size. This will only work in combination with the "px" parameter as the original image is returned when the "px" parameter is omitted which is always available, so there will never be a fallback to the "minAcceptableSize" 

+ Response 200

    + Headers

            Date: 2017-04-01T01:00:00.000Z
            Content-Type: image/jpeg
            
    + Body
    
            Binary Image Data

+ Response 404

    + Headers

            Content-Type: application/json
            
    + Body
    
            {
                "type": "NotFoundError",
                "message": "This resource could not be found."
            }

### GET Product prices [GET /products/prices/{?token,brand,gtins,updatedSince,limit,afterId}]

This endpoint returns your retail specific prices for a specific brand or subset of a brand's prices
* note that prices are specific to a retailer. When building solutions that fit multiple retailers, please store prices per retailer. 

+ Parameters
    + token (String, required) - Your Fashion Cloud API Key/Token
    + brand (String, required) - The brand id that you can retrieve from the /brands endpoint
    + gtins (comma separated string, optional) - The GTIN(s) of the products to get prices for
    + updatedSince (ISO Date String, optional) - Only get prices that have been updated or created since the given date
    + limit (Number, optional) - The amount of items to return per page (default = 200), optional, max value is 200
    + afterId (String, optional) - The "nextId" of the response body in order to get the next page 

+ Response 200
    + Headers
    
            Date:2017-04-01T01:00:00.000Z
            Content-Type: application/json
    + Body
    
            {
            "totalElements": 2,
            "data": [
                {
                    "gtin": "8719936125740",
                    "currency": "EUR",
                    "purchasePrice": 33.31,
                    "discountedPurchasePrice": null,
                    "recommendedRetailPrice": 89.95,
                    "discountedRecommendedRetailPrice": null,
                    "updated": "2022-01-22T22:14:04.256Z"
                },
                {
                    "gtin": "8719936125757",
                    "currency": "EUR",
                    "purchasePrice": 33.31,
                    "discountedPurchasePrice": null,
                    "recommendedRetailPrice": 89.95,
                    "discountedRecommendedRetailPrice": null,
                    "updated": "2022-01-22T22:14:04.256Z"
            }
            ],
            "afterId": "61e88c5cf7449d00119c1a99",
            "limit": 200,
            "nextId": "61ec81acf2beee00157d6cee"
            }

## Stock data [/products/{gtin}/stock{?token}]

### GET Product's Stock API [GET]

Additional information:

   * This API can be used to request an item's availability in its actual physical (brands) storage. You can only get one gtin's stock value at a time. 
   * Our API might return capped stock values to protect the brands valuable real stock data.


+ Parameters
    + gtin (String) - The GTIN of the product
    + token (String) - Your Fashion Cloud API Key/Token, mandatory

+ Response 200

    + Headers

            Date: 2017-04-01T01:00:00.000Z
            Content-Type: application/json
            
    + Body
    
            {
                "stock": 10,
                "deliveryTime": {
                    "minimum": 2,
                    "maximum": 3
                },
                "created": "2016-12-01T01:00:00.000Z",
                "updated": "2016-12-02T01:00:00.000Z"
            }

+ Response 400

    + Headers

            Content-Type: application/json
            
    + Body
    
            {
                "type": "InvalidParametersError",
                "message": "The provided parameters are illegal."
            }

+ Response 401

    + Headers


            Content-Type: application/json
            
    + Body
    
            {
                "type": "InvalidApiKeyError",
                "message": "Your api key is invalid or missing."
            }

## Orders [/orders{?token}]

### POST Order API [POST]
Additional information:

* This API is for endless aisle purpose only.

* When you POST an order Fashion Cloud will first do a final check if the requested items are in stock. If they are, the order will be processed and you'll get a 200 Response. If one or more items aren't available in the requested quantity or aren't available anymore at all, you'll get a detailed response about it (see Response `type: "OrderingProcessError"`).
    
* The main difference between our v1 and v2 Order API is the v2's support for full shopping cart functionality. Our Order API can consume multiple EAN's from multiple brands in a single order.

* Unlike our v1 Order API, the property `type` does not longer define whether it's a test order or not. You have to send `isTest: "true"` in order to send test orders. These orders won't trigger a real order but will show you the proper responses to see if you have the proper information in your request body. For testing, you need to have access to endless aisle for at least one brand. Please contact us if you do need help in setting up a test account.



+ Parameters
    + token (String) - Your Fashion Cloud API Key/Token, mandatory

+ Request

    + Headers

            Content-Type: application/json

    + Body

            {
            "products": [{ // max entries = 1000
                "gtin": "1234567890123",
                "quantity": 10
            }],
            "clientId": "asd2123-123", //mandatory for endless aisle, erp & other "order sources" can leave it empty
            "clientType": "erp" // clara, erp, fc-platform (has to be "erp", fc-platform & clara are so far only used internally at Fashion Cloud)
            "debitor": {
                "gln": "1234567890123", // mandatory only for type = endless-aisle. Put your Buyer GLN in here. If you don't have one, simply put your shipping GLN in here as well.
                "phone": "+49 40 22 86 24 20", // optional
                "name": "Fashion Cloud", // optional
                "email": "info@fashion.cloud", // mandatory only for type = b2b-order
                "employeeId": "abc123", // optional
                "employeeName": "John Doe" // optional
            },
            "shippingAddress": {
                "gln": "45678912344", //  mandatory for type = erp & endless-aisle. This is the minimum required information Fashion Cloud & the brands need in order to know where to ship the parcel to.
                "email": "john@example.com", // optional
                "phone": "01762343211", // optional
                "name": "John Doe",
                "address1": "Hongkongstrasse 1",
                "address2": "3rd floor", // optional
                "city": "Hamburg",
                "zip": "20457",
                "country": "DE"
            },
            "billingAddress": { // optional
                "gln": "45678912344", // optional
                "email": "john@example.com", // optional
                "phone": "01762343211", // optional
                "name": "John Doe",
                "address1": "Hongkongstrasse 1",
                "address2": "3rd floor", // optional
                "city": "Hamburg",
                "zip": "20457",
                "country": "DE"
            },
            "endCustomer": { // optional
                "customerNumber": "abc123", // optional
                "name": "John Doe", // optional
                "email": "john@example.com", // optional
                "phone": "01762343211" // optional
            },
            "useDropshipping": false, // optional; boolean; Note: the dropshipping feature is only fully supported by a limited number of brands, and is experimental for some of the brands. Please contact the customer support prior to using the feature
            "type": "endless-aisle", // endless-aisle, b2b-order (b2b-order is so far only used internally at Fashion Cloud)
            "isTest": false
            }

+ Response 200 (application/json)

    + Headers

            Date: 2017-04-01T01:00:00.000Z

    + Body
    
            {
                "_id": "123456",
                "orderNumber": "FC2345812",
                "status": "open"
            }

+ Response 400 (application/json)

    + Body
    
            {
                "type": "ValidationError",
                "message": "The provided parameters are invalid",
                "errors": [
                    {
                        "field": "products",
                        "type": "isEmpty",
                        "message": "Field should not be empty"
                    },
                    { 
                        "field": "clientId",
                        "type": "isNotPresent",
                        "message": "Field should be present"
                    }
                ]
            }
        
+ Response 400 (application/json)

    + Body
    
            {
                "type": "OrderingProcessError",
                "message": "The order could not be processed",
                "errors": [
                    {
                        "type": "InsufficientQuantity",
                        "message": "There is not enough stock available for this product",
                        "orderedQuantity": 1000,
                        "availableQuantity": 120,
                        "gtin": "4044816620478"
                    }
                ]
            }
